version: '3.5'

services: 
    angular-service:
        container_name: angular-container1
        build: ./
        volumes: 
        - './:/user/src/app'
        ports:
            - "4200:4200"
        command: >
            bash -c "npm start"
    docker-nginx:
        container_name: docker-nginx
        build: ./
        ports:
            - "4200:80"
        command: ["nginx", "-g", "daemon off;"]
        links:
            - angular-service
    db:
        image: mysql:latest
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: app_db
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
    springboot-service:
        container_name: spring-backend
        #build: .\./Documents/workspace-spring-tool-suite-4-4.4.1.RELEASE/VideoStore/
        #build: ../../
        build: ..\..\Documents\workspace-spring-tool-suite-4-4.4.1.RELEASE\VideoStore\
        depends_on: 
            - db
volumes:
    dbdata: